# Generated by Django 2.2.28 on 2024-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('persId', models.IntegerField(db_column='pers_id', primary_key=True, serialize=False)),
                ('empOrgNo', models.IntegerField(db_column='emp_org_no')),
                ('divNo', models.SmallIntegerField(db_column='div_no')),
                ('pfnSurname', models.CharField(db_column='pfn_surname', max_length=64)),
                ('pfnName', models.CharField(db_column='pfn_name', max_length=64)),
                ('pfnPatronymic', models.CharField(db_column='pfn_patronymic', max_length=64)),
                ('pqlfName', models.CharField(db_column='pqlf_name', max_length=256)),
                ('profName', models.CharField(db_column='prof_name', max_length=256)),
                ('empChangesDate', models.DateField(db_column='emp_changes_date')),
                ('empDismissDate', models.DateField(blank=True, db_column='emp_dismiss_date', null=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
                'permissions': [('load_employees', 'Загрузка сотрудников'), ('view_employees', 'Просмотр сотрудников')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('xv26eiId', models.IntegerField(db_column='xv26ei_id', primary_key=True, serialize=False)),
                ('xv26eicYear', models.SmallIntegerField(db_column='xv26eic_year')),
                ('xv26eihDateBegin', models.DateField(db_column='xv26eih_date_begin')),
                ('xv26eihDateEnd', models.DateField(blank=True, db_column='xv26eih_date_end', null=True)),
                ('xv26eihName', models.CharField(db_column='xv26eih_name', max_length=200)),
                ('xv26eirSumPlan', models.DecimalField(db_column='xv26eir_sum_plan', decimal_places=4, max_digits=19)),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Сметы',
                'db_table': 'estimate',
                'permissions': [('load_estimates', 'Загрузка смет'), ('view_estimates', 'Просмотр смет')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('pdId', models.IntegerField(db_column='pd_id', primary_key=True, serialize=False)),
                ('pdSource', models.SmallIntegerField(db_column='pd_source')),
                ('empOrgNo', models.IntegerField(db_column='emp_org_no')),
                ('xv26eiId', models.SmallIntegerField(blank=True, db_column='xv26ei_id', null=True)),
                ('orderId', models.CharField(blank=True, db_column='order_id', max_length=20, null=True)),
                ('orderIdUpd', models.CharField(blank=True, db_column='order_id_upd', max_length=20, null=True)),
                ('orderNo', models.CharField(blank=True, db_column='order_no', max_length=100, null=True)),
                ('orderDate', models.DateField(blank=True, db_column='order_date', null=True)),
                ('bic', models.IntegerField(blank=True, db_column='bic', null=True)),
                ('sum', models.DecimalField(db_column='sum', decimal_places=2, max_digits=10)),
                ('acplAccount', models.SmallIntegerField(blank=True, db_column='acpl_account', null=True)),
                ('acplSubaccount', models.SmallIntegerField(blank=True, db_column='acpl_subaccount', null=True)),
            ],
            options={
                'verbose_name': 'Аванс',
                'verbose_name_plural': 'Авансы',
                'db_table': 'prepayment',
                'permissions': [('load_prepayments', 'Загрузка авансов'), ('view_prepayments', 'Просмотр авансов')],
                'default_permissions': (),
            },
        ),
    ]
