# Generated by Django 2.2.28 on 2024-06-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'default_permissions': (), 'permissions': [('load_employees', 'Загрузка'), ('view_employees', 'Просмотр')], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='estimate',
            options={'default_permissions': (), 'permissions': [('load_estimates', 'Загрузка'), ('view_estimates', 'Просмотр')], 'verbose_name': 'Смета', 'verbose_name_plural': 'Сметы'},
        ),
        migrations.AlterModelOptions(
            name='prepayment',
            options={'default_permissions': (), 'permissions': [('load_prepayments', 'Загрузка'), ('view_prepayments', 'Просмотр')], 'verbose_name': 'Аванс', 'verbose_name_plural': 'Авансы'},
        ),
    ]
