# Generated by Django 2.2.28 on 2024-06-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_auto_20240606_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='WC07POrder',
            fields=[
                ('orderName', models.CharField(blank=True, db_column='order_name', max_length=200, null=True)),
                ('orderId', models.CharField(db_column='order_id', max_length=20, primary_key=True, serialize=False)),
                ('orderNum', models.CharField(blank=True, db_column='order_num', max_length=50, null=True)),
                ('orderDate', models.DateField(blank=True, db_column='order_date', null=True)),
                ('empOrgNo', models.IntegerField(db_column='emp_org_no')),
                ('depName', models.CharField(blank=True, db_column='dep_name', max_length=200, null=True)),
                ('fio', models.CharField(blank=True, db_column='fio', max_length=200, null=True)),
                ('profName', models.CharField(blank=True, db_column='prof_name', max_length=256, null=True)),
                ('distName', models.CharField(blank=True, db_column='dist_name', max_length=500, null=True)),
                ('missionBegin', models.DateField(blank=True, db_column='mission_begin', null=True)),
                ('missionEnd', models.DateField(blank=True, db_column='mission_end', null=True)),
                ('missionPurpose', models.CharField(blank=True, db_column='mission_purpose', max_length=500, null=True)),
                ('estimateId', models.IntegerField(blank=True, db_column='estimate_id', null=True)),
                ('payDoc', models.CharField(blank=True, db_column='pay_doc', max_length=20, null=True)),
                ('orderIdUpd', models.CharField(blank=True, db_column='order_id_upd', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
                'db_table': 'wc07p_order',
                'permissions': [('load_orders', 'Загрузка'), ('view_orders', 'Просмотр')],
                'default_permissions': (),
            },
        ),
    ]
