# Generated by Django 2.2.28 on 2024-06-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_wc07porder'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prepayment',
            table='integration_prepayment',
        ),
    ]
