# Generated by Django 2.2.28 on 2024-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_auto_20240616_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('operDate', models.DateTimeField(db_column='oper_date')),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Протокол обмена',
                'verbose_name_plural': 'Протоколы обмена',
                'db_table': 'exchange_protocol',
                'permissions': [('view_exchange_protocol', 'Просмотр')],
                'default_permissions': (),
            },
        ),
    ]
