# Generated by Django 2.2.28 on 2025-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_exchangeprotocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wc07porder',
            name='payDoc',
            field=models.CharField(blank=True, db_column='pay_doc', max_length=100, null=True),
        ),
    ]
