# Generated by Django 2.2.28 on 2025-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_auto_20250603_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accountNumber',
            field=models.CharField(blank=True, db_column='account_number', max_length=20, null=True, verbose_name='Номер лицевого счета'),
        ),
        migrations.AddField(
            model_name='employee',
            name='snils',
            field=models.CharField(blank=True, db_column='snils', max_length=11, null=True, verbose_name='СНИЛС'),
        ),
    ]
