# Generated by Django 2.2.28 on 2025-07-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_auto_20250701_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wc07porder',
            name='orderIdUpd',
            field=models.CharField(blank=True, db_column='order_id_upd', max_length=40, null=True),
        ),
    ]
