# Generated by Django 2.2.28 on 2025-12-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_auto_20250711_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='accountNumber',
            field=models.CharField(blank=True, db_column='account_number', max_length=2000, null=True, verbose_name='Номер лицевого счета'),
        ),
    ]
