# Generated by Django 4.2.16 on 2026-03-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0009_auto_20251217_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='wc07porder',
            name='advanceDate',
            field=models.DateField(blank=True, db_column='advance_date', null=True),
        ),
        migrations.AddField(
            model_name='wc07porder',
            name='advanceSum',
            field=models.DecimalField(blank=True, db_column='advance_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wc07porder',
            name='balanceAccount',
            field=models.IntegerField(blank=True, db_column='balance_account', null=True),
        ),
        migrations.AddField(
            model_name='wc07porder',
            name='bik',
            field=models.IntegerField(blank=True, db_column='bik', null=True),
        ),
    ]
