# Generated by Django 2.2.28 on 2024-06-07 15:19

from django.db import migrations, models

def insert_initial_data (apps, schema_editor):
    imprestAccount = apps.get_model('guide', 'ImprestAccount')
    imprestAccount.objects.create (name = 'Расходы по командировкам', account = '7101')
    imprestAccount.objects.create (name = 'расходы по загранкомандировкам ', account = '7102')
    imprestAccount.objects.create (name = 'Расходы 013 цеха', account = '7103')
    imprestAccount.objects.create (name = 'Расходы по приобретению ТМЦ, работ, услуг', account = '7104')
    imprestAccount.objects.create (name = 'Расходы 075 отдела', account = '7105')
    imprestAccount.objects.create (name = 'Расходы по приобретению ТМЦ, работ, услуг г. Москва', account = '7106')
    imprestAccount.objects.create (name = 'Расходы 900 отдела', account = '7108')

    expenseCode = apps.get_model('guide', 'ExpenseCode')
    expenseCode.objects.create (name = 'Расходы по командировкам', code = '00')
    expenseCode.objects.create (name = 'Расходы по командировкам с отнесешем затрат на заказ', code = '01')
    expenseCode.objects.create (name = 'Расходы по командировкам, связанные с заготовлением МПЗ', code = '16')
    expenseCode.objects.create (name = 'Расходы по загранкомандировкам', code = '30')
    expenseCode.objects.create (name = 'Расходы по командировкам, связанные с обучением. повышением квалификации, подготовкой кадров', code = '69')
    expenseCode.objects.create (name = 'Расходы по командировкам, источник 91 счет "Прочие расходы"', code = '91')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCode',
            fields=[
                ('code', models.CharField(db_column='code', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Код расхода',
                'verbose_name_plural': 'Коды расходов',
                'db_table': 'expense_code',
                'permissions': [('view_expense_codes', 'Просмотр'), ('edit_expense_codes', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ImprestAccount',
            fields=[
                ('account', models.IntegerField(db_column='account', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Код учета подотчетной суммы',
                'verbose_name_plural': 'Коды учета подотчетной суммы',
                'db_table': 'imprest_account',
                'permissions': [('view_imprest_accounts', 'Просмотр'), ('edit_imprest_accounts', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.RunPython(insert_initial_data)
    ]
