# Generated by Django 2.2.28 on 2024-06-10 11:08

from django.db import migrations, models

def insert_initial_data (apps, schema_editor):
    expenseCategory = apps.get_model('guide', 'ExpenseCategory')
    expenseCategory.objects.create (name = 'Не командировочные расходы (по заявлению за счет прочих расходов), источник 91 счет "Прочие расходы"', num = '9.7', printName='Расходы по заявлению')
    expenseCategory.objects.create (name = 'Не командировочные расходы (по заявлению)', num = '4.8', printName='Расходы по заявлению')
    expenseCategory.objects.create (name = 'Проезд (неучитываемый в целях налогообложения прибыли)', num = '2.4', printName='Проезд')
    expenseCategory.objects.create (name = 'Проезд авиатранспортом', num = '2.3', printName='Проезд')
    expenseCategory.objects.create (name = 'Проезд авиатранспортом (без НДС), источник 91 счет "Прочие расходы"', num = '7.3', printName='Проезд')
    expenseCategory.objects.create (name = 'Проезд автомобильным транспортом', num = '2.1', printName='Проезд')
    expenseCategory.objects.create (name = 'Проезд автомобильным транспортом (без НДС), источник 91 счет "Прочие расходы"', num = '7.1', printName='Проезд')
    expenseCategory.objects.create (name = 'Проезд без документов (по заявлению)', num = '2.5', printName='Проезд без документов')
    expenseCategory.objects.create (name = 'Проезд железнодорожным транспортом', num = '2.2', printName='Проезд')
    expenseCategory.objects.create (name = 'Проезд железнодорожным транспортом (без НДС), источник 91 счет "Прочие расходы"', num = '7.2', printName='Проезд')
    expenseCategory.objects.create (name = 'Проезда без документов (по заявлению), источник 91 счет "Прочие расходы"', num = '7.4', printName='Проезд без документов')
    expenseCategory.objects.create (name = 'Проживание  (не учитываемое в целях налогообложения прибыли)', num = '3.2', printName='Проживание')
    expenseCategory.objects.create (name = 'Проживание (без НДС), источник 91 счет "Прочие расходы"', num = '8.1', printName='Проживание')
    expenseCategory.objects.create (name = 'Проживание (счет, акт, договор)', num = '3.1', printName='Проживание')
    expenseCategory.objects.create (name = 'Проживание без документов в пределах норм', num = '3.4', printName='Проживание без документов')
    expenseCategory.objects.create (name = 'Проживание без документов в пределах норм (акт цеха 013)', num = '3.5', printName='Проживание без документов')
    expenseCategory.objects.create (name = 'Проживание без документов в пределах норм (акт цеха 013), источник 91 счет "Прочие расходы"', num = '8.4', printName='Проживание без документов')
    expenseCategory.objects.create (name = 'Проживание без документов в пределах норм, источник 91 счет "Прочие расходы"', num = '8.3', printName='Проживание без документов')
    expenseCategory.objects.create (name = 'Проживание без документов сверх норм (акт цеха 013)', num = '3.6', printName='Проживание без документов сверх норм')
    expenseCategory.objects.create (name = 'Проживание без документов сверх норм (акт цеха 013), источник 91 счет "Прочие расходы"', num = '8.5', printName='Проживание без документов сверх норм')
    expenseCategory.objects.create (name = 'Прочие расходы (курсовые разницы)', num = '4.6', printName='Курсовая разница')
    expenseCategory.objects.create (name = 'Прочие расходы (курсовые разницы), источник 91 счет "Прочие расходы"', num = '9.6', printName='Курсовая разница')
    expenseCategory.objects.create (name = 'Прочие расходы (проведение теста на COVID)', num = '4.9', printName='Тест на COVID')
    expenseCategory.objects.create (name = 'Прочие расходы (проведение теста на COVID), источник 91 счет "Прочие расходы"', num = '9.8', printName='Тест на COVID')
    expenseCategory.objects.create (name = 'Прочие расходы (расходы, связанные с возвратом и переоформлением проездных билетов)', num = '4.5', printName='Прочие расходы')
    expenseCategory.objects.create (name = 'Прочие расходы (расходы, связанные с возвратом и переоформлением проездных билетов), источник 91 счет "Прочие расходы"', num = '9.5', printName='Прочие расходы')
    expenseCategory.objects.create (name = 'Прочие расходы (расходы, связанные с оплатой услуг VIP-залов)', num = '4.4', printName='Прочие расходы')
    expenseCategory.objects.create (name = 'Прочие расходы (расходы, связанные с оплатой услуг VIP-залов), источник 91 счет "Прочие расходы"', num = '9.4', printName='Прочие расходы')
    expenseCategory.objects.create (name = 'Прочие расходы (расходы, связанные с провозом, хранением багажа, оплатой услуг связи и др.аналогичные расходы)', num = '4.3', printName='Прочие расходы')
    expenseCategory.objects.create (name = 'Прочие расходы (расходы, связанные с провозом, хранением багажа, оплатой услуг связи и др.аналогичные расходы), источник 91 счет "Прочие расходы"', num = '9.3', printName='Прочие расходы')
    expenseCategory.objects.create (name = 'Прочие расходы (сбор за право въезда, прохода, транзита транспорта и другие аналогичные платежи и сборы)', num = '4.1', printName='Прочие расходы')
    expenseCategory.objects.create (name = 'Прочие расходы (сбор за право въезда, прохода, транзита транспорта и другие аналогичные платежи и сборы), источник 91 счет "Прочие расходы"', num = '9.1', printName='Прочие расходы')
    expenseCategory.objects.create (name = 'Прочие расходы, связанные с зарубежной командировкой (консульские сборы, расходы по оформлению и выдаче виз, служебных загранпаспортов, приглашений и др., в т.ч. мед.страховка)', num = '4.2', printName='Прочие расходы')
    expenseCategory.objects.create (name = 'Прочие расходы, связанные с зарубежной командировкой (консульские сборы, расходы по оформлению и выдаче виз, служебных загранпаспортов, приглашений и др., в т.ч. мед.страховка), источник 91 счет "Прочие расходы"', num = '9.2', printName='Прочие расходы')
    expenseCategory.objects.create (name = 'Стоянка (парковка) служебного транспорта', num = '5.1', printName='Стоянка')
    expenseCategory.objects.create (name = 'Стоянка (парковка) служебного транспорта (без НДС), источник 91 счет "Прочие расходы"', num = '10', printName='Стоянка')
    expenseCategory.objects.create (name = 'Стоянка (парковка) служебного транспорта (не учитываемый в целях налогообложения прибыли)', num = '5.2', printName='Стоянка')
    expenseCategory.objects.create (name = 'Суточные в пределах норм', num = '1.1', printName='Суточные')
    expenseCategory.objects.create (name = 'Суточные в пределах норм, источник 91 счет "Прочие расходы"', num = '6.1', printName='Суточные')
    expenseCategory.objects.create (name = 'Суточные сверх норм', num = '1.2', printName='Суточные сверх норм')
    expenseCategory.objects.create (name = 'Суточные сверх норм, источник 91 счет "Прочие расходы"', num = '6.2', printName='Суточные сверх норм')
    expenseCategory.objects.create (name = 'Услуги гостиницы, облагаемые НДФЛ', num = '3.3', printName='Услуги гостиницы')
    expenseCategory.objects.create (name = 'Услуги гостиницы, облагаемые НДФЛ, источник 91 счет "Прочие расходы"', num = '8.2', printName='Услуги гостиницы')

    expenseCategory.objects.create (name = 'ТМЦ / приход через склад по  товарному, кассовому чеку', num = '11.1', printName='ТМЦ')
    expenseCategory.objects.create (name = 'ТМЦ / приход через склад по счету-фактуре, УПД', num = '11.2', printName='ТМЦ')
    expenseCategory.objects.create (name = 'Бензин, упрощенный приход', num = '12.1', printName='Бензин')
    expenseCategory.objects.create (name = 'ДИЗ топливо, упрощенный приход', num = '12.2', printName='ДИЗ топливо')
    expenseCategory.objects.create (name = 'Метан, упрощенный приход', num = '12.3', printName='Метан')
    expenseCategory.objects.create (name = 'Масла, упрощенный приход', num = '12.4', printName='Масло')
    expenseCategory.objects.create (name = 'Запчасти, упрощенный приход', num = '12.5', printName='Запчасти')
    expenseCategory.objects.create (name = 'Материалы для цеха 013 при ремонте, упрощенный приход', num = '12.6', printName='Материалы')
    expenseCategory.objects.create (name = 'Материалы (СОЖ), упрощенный приход', num = '12.7', printName='СОЖ')
    expenseCategory.objects.create (name = 'Представительские расходы / ТМЦ / товарный, кассовый чек', num = '13.1', printName='ТМЦ')
    expenseCategory.objects.create (name = 'Представительские расходы / услуги / кассовый чек', num = '13.1', printName='Услуги')
    expenseCategory.objects.create (name = 'Представительские расходы / ТМЦ / cчет-фактура, УПД', num = '13.2', printName='ТМЦ')
    expenseCategory.objects.create (name = 'Представительские расходы / услуги / cчет-фактура, УПД', num = '13.2', printName='Услуги')
    expenseCategory.objects.create (name = 'Представительские расходы / услуги / кассовый чек', num = '13.3', printName='Услуги')
    expenseCategory.objects.create (name = 'Представительские расходы / услуги /  cчет-фактура, УПД', num = '13.4', printName='Услуги')
    expenseCategory.objects.create (name = 'Представительские расходы / услуги / cчет-фактура, УПД', num = '13.4', printName='Услуги')
    expenseCategory.objects.create (name = 'Работы, услуги / кассовый чек', num = '14.1', printName='Услуги')
    expenseCategory.objects.create (name = 'Работы, услуги / cчет-фактура, УПД', num = '14.2', printName='Услуги')
    expenseCategory.objects.create (name = 'Работы, услуги для цеха 013 / заказ-наряд ', num = '15', printName='Услуги')
    expenseCategory.objects.create (name = 'Работы, услуги для отдела (г.Москва) / Счет-фактура,УПД', num = '16', printName='Услуги')


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_expenserate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(db_column='num', max_length=10)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('printName', models.CharField(blank=True, db_column='print_name', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'verbose_name_plural': 'Категории расходов',
                'db_table': 'expense_category',
                'permissions': [('view_expense_categories', 'Просмотр'), ('edit_expense_categories', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.RunPython(insert_initial_data)
    ]
