# Generated by Django 2.2.28 on 2024-06-10 16:55

from django.db import migrations, models

def insert_initial_data (apps, schema_editor):
    document = apps.get_model('guide', 'Document')
    document.objects.create (name = 'Акт', id = '1')
    document.objects.create (name = 'Билет', id = '2')
    document.objects.create (name = 'Договор-счет', id = '3')
    document.objects.create (name = 'Заказ-наряд', id = '4')
    document.objects.create (name = 'Заявление', id = '5')
    document.objects.create (name = 'Кассовый чек', id = '6')
    document.objects.create (name = 'Квитанция', id = '7')
    document.objects.create (name = 'Квитанция разных сборов', id = '8')
    document.objects.create (name = 'Маршрутная квитанция электронного билета', id = '9')
    document.objects.create (name = 'Сервисный сбор', id = '10')
    document.objects.create (name = 'Счет', id = '11')
    document.objects.create (name = 'Счет-фактура', id = '12')
    document.objects.create (name = 'Электронный билет', id = '13')


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_expenseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'document',
                'permissions': [('view_document', 'Просмотр'), ('edit_document', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.RunPython(insert_initial_data)
    ]
