# Generated by Django 2.2.28 on 2024-06-10 18:42

from django.db import migrations, models


def insert_initial_data (apps, schema_editor):
    accountingCert = apps.get_model('guide', 'AccountingCert')
    accountingCert.objects.create (num = '57000', account = '7101')
    accountingCert.objects.create (num = '57300', account = '7102')
    accountingCert.objects.create (num = '57700', account = '7103')
    accountingCert.objects.create (num = '57600', account = '7104')
    accountingCert.objects.create (num = '57400', account = '7105')
    accountingCert.objects.create (num = '58300', account = '7106')
    accountingCert.objects.create (num = '90001', account = '7108')


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingCert',
            fields=[
                ('account', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.CharField(db_column='num', max_length=10)),
            ],
            options={
                'verbose_name': 'Бухгалтерская справка',
                'verbose_name_plural': 'Бухгалтерские справки',
                'db_table': 'accounting_cert',
                'permissions': [('view_accounting_cert', 'Просмотр'), ('edit_accounting_cert', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.RunPython(insert_initial_data)
    ]
