# Generated by Django 2.2.28 on 2024-06-10 19:02

from django.db import migrations, models

def insert_initial_data (apps, schema_editor):
    status = apps.get_model('guide', 'Status')
    status.objects.create (name = 'Загружен', id = '1')
    status.objects.create (name = 'Подготовлен', id = '2')
    status.objects.create (name = 'Согласован', id = '3')
    status.objects.create (name = 'Не согласован', id = '4')
    status.objects.create (name = 'Удтвержден', id = '5')
    


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_accountingcert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
                'permissions': [('view_status', 'Просмотр'), ('edit_status', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.RunPython(insert_initial_data)
    ]
