# Generated by Django 2.2.28 on 2024-06-11 13:01

from django.db import migrations, models

def insert_initial_data (apps, schema_editor):
    obtainMethod = apps.get_model('guide', 'ObtainMethod')
    obtainMethod.objects.create (name='Касса', source='0')
    obtainMethod.objects.create (name='ГПБ', source='1', bik='044525823')
    obtainMethod.objects.create (name='СБ', source='1', bik='046577674')
    obtainMethod.objects.create (name='ВТБ', source='1', bik='046577501')
    obtainMethod.objects.create (name='УБРиР', source='1', bik='046577795')
    obtainMethod.objects.create (name='Открытие', source='1', bik='044525297')
    obtainMethod.objects.create (name='Тинькофф', source='1', bik='044525974')
    obtainMethod.objects.create (name='Заработная плата')


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_departmentaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObtainMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('source', models.SmallIntegerField(blank=True, db_column='source', null=True)),
                ('bik', models.IntegerField(blank=True, db_column='bik', null=True)),
            ],
            options={
                'verbose_name': 'Способ получения',
                'verbose_name_plural': 'Способы получения',
                'db_table': 'obtain_method',
                'permissions': [('view_obtain_method', 'Просмотр'), ('edit_obtain_method', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.RunPython(insert_initial_data)
    ]
