# Generated by Django 2.2.28 on 2024-06-11 13:42

from django.db import migrations, models

def insert_initial_data (apps, schema_editor):
    prepaidDest = apps.get_model('guide', 'PrepaidDest')
    prepaidDest.objects.create (name='Командировочные расходы')
    prepaidDest.objects.create (name='Расходы по приобретению ТМЦ, работ, услуг')
    prepaidDest.objects.create (name='Представительские расходы')
    prepaidDest.objects.create (name='Служебная поездка')

class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_obtainmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidDest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
            ],
            options={
                'verbose_name': 'Назначение аванса',
                'verbose_name_plural': 'Назначения аванса',
                'db_table': 'prepaid_dest',
                'permissions': [('view_prepaid_dest', 'Просмотр'), ('edit_prepaid_dest', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.RunPython(insert_initial_data)
    ]
