# Generated by Django 2.2.28 on 2024-07-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_prepaiddest'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='expenseType',
            field=models.SmallIntegerField(blank=True, db_column='expense_type', null=True),
        ),
    ]
