# Generated by Django 2.2.28 on 2024-08-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_expenseitem_expensetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='debitExpenseDept',
            field=models.SmallIntegerField(blank=True, db_column='debit_expense_dept', null=True),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='debitExpenseItem',
            field=models.SmallIntegerField(blank=True, db_column='debit_expense_item', null=True),
        ),
    ]
