# Generated by Django 2.2.28 on 2024-08-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_auto_20240830_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='creditExpenseDept',
            field=models.SmallIntegerField(blank=True, db_column='credit_expense_dept', null=True),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='creditExpenseItem',
            field=models.SmallIntegerField(blank=True, db_column='credit_expense_item', null=True),
        ),
    ]
