# Generated by Django 2.2.28 on 2024-11-11 17:52

from django.db import migrations, models

def insert_initial_data (apps, schema_editor):
    refundExpense = apps.get_model('guide', 'RefundExpense')
    refundExpense.objects.create (id = '1', payKind=4479, codeName='4.9', name='Прочие расходы (проведение теста на COVID)', code='091')
    refundExpense.objects.create (id = '2', payKind=7121, codeName='3.4', name='Проживание без документов в пределах норм', code='290')
    refundExpense.objects.create (id = '3', payKind=7121, codeName='8.3', name='Проживание без документов в пределах норм, источник 91 счет "Прочие расходы"', code='290')
    refundExpense.objects.create (id = '4', payKind=7130, codeName='1.2', name='Суточные сверх норм', code='011')
    refundExpense.objects.create (id = '5', payKind=7130, codeName='6.2', name='Суточные сверх норм, источник 91 счет "Прочие расходы"', code='211')
    refundExpense.objects.create (id = '6', payKind=7140, codeName='2.5', name='Проезд без документов (по заявлению)', code='281')
    refundExpense.objects.create (id = '7', payKind=7140, codeName='3.3', name='Услуги гостиницы, облагаемые НДФЛ', code='251')
    refundExpense.objects.create (id = '8', payKind=7140, codeName='4.8', name='Не командировочные расходы (по заявлению)', code='271')
    refundExpense.objects.create (id = '9', payKind=7140, codeName='7.4', name='Проезда без документов (по заявлению), источник 91 счет "Прочие расходы"', code='281')

class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0014_auto_20240830_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payKind', models.IntegerField(db_column='pay_kind')),
                ('codeName', models.CharField(db_column='code_name', max_length=10)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('code', models.CharField(db_column='code', max_length=10)),
            ],
            options={
                'verbose_name': 'Возмещаемые расходы',
                'verbose_name_plural': 'Возмещаемые расходы',
                'db_table': 'refund_expense',
                'permissions': [('view_refund_expenses', 'Просмотр'), ('edit_refund_expenses', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.RunPython(insert_initial_data)
    ]
