# Generated by Django 2.2.28 on 2024-11-11 17:52

from django.db import migrations, models

def update_data (apps, schema_editor):
    refundExpense = apps.get_model('guide', 'AccountingCert')
    refundExpense.objects.filter(account=7101).update(num=57001)
    refundExpense.objects.filter(account=7105).update(num=57401)

class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0015_refundexpense'),
    ]

    operations = [
        migrations.RunPython(update_data)
    ]
