# Generated by Django 2.2.28 on 2025-01-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0016_updateAccountingCerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
