# Generated by Django 2.2.28 on 2025-01-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0018_auto_20250127_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingcert',
            name='account',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='accountingcert',
            name='num',
            field=models.CharField(db_column='num', max_length=10, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='obtainmethod',
            name='bik',
            field=models.IntegerField(blank=True, db_column='bik', null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='obtainmethod',
            name='name',
            field=models.CharField(db_column='name', max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='obtainmethod',
            name='source',
            field=models.SmallIntegerField(blank=True, db_column='source', null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(db_column='name', max_length=50, verbose_name='Наименование'),
        ),
    ]
