# Generated by Django 2.2.28 on 2025-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0020_obtainmethod_clientnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='obtainmethod',
            name='registerCounter',
            field=models.IntegerField(blank=True, db_column='register_counter', null=True, verbose_name='Номер реестра'),
        ),
    ]
