# Generated by Django 2.2.28 on 2025-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0022_auto_20250619_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='obtainmethod',
            name='bAccount',
            field=models.CharField(blank=True, db_column='b_account', max_length=10, null=True, verbose_name='Б/счет'),
        ),
        migrations.AddField(
            model_name='obtainmethod',
            name='corrAccount',
            field=models.CharField(blank=True, db_column='corr_account', max_length=20, null=True, verbose_name='Кор. счет'),
        ),
        migrations.AddField(
            model_name='obtainmethod',
            name='currentAccount',
            field=models.CharField(blank=True, db_column='current_account', max_length=20, null=True, verbose_name='Р/счет'),
        ),
        migrations.AddField(
            model_name='obtainmethod',
            name='inn',
            field=models.CharField(blank=True, db_column='inn', max_length=10, null=True, verbose_name='ИНН банка'),
        ),
        migrations.AddField(
            model_name='obtainmethod',
            name='kpp',
            field=models.CharField(blank=True, db_column='kpp', max_length=9, null=True, verbose_name='КПП банка'),
        ),
        migrations.AddField(
            model_name='obtainmethod',
            name='printName',
            field=models.CharField(blank=True, db_column='print_name', max_length=40, null=True, verbose_name='Для печати'),
        ),
    ]
