# Generated by Django 2.2.28 on 2025-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0023_auto_20250620_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtainmethod',
            name='bAccount',
            field=models.CharField(blank=True, db_column='b_account', max_length=10, null=True, verbose_name='Бал./счет'),
        ),
    ]
