# Generated by Django 2.2.28 on 2025-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0024_auto_20250624_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='obtainmethod',
            name='creditAccount',
            field=models.CharField(blank=True, db_column='credit_account', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='obtainmethod',
            name='creditKAU1',
            field=models.CharField(blank=True, db_column='credit_kau_1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='obtainmethod',
            name='creditKAU2',
            field=models.CharField(blank=True, db_column='credit_kau_2', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='obtainmethod',
            name='creditSubaccount',
            field=models.CharField(blank=True, db_column='credit_subaccount', max_length=2, null=True),
        ),
    ]
