# Generated by Django 2.2.28 on 2025-06-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0025_auto_20250627_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='obtainmethod',
            name='debitExtra',
            field=models.CharField(blank=True, db_column='debit_extra', max_length=10, null=True),
        ),
    ]
