# Generated by Django 2.2.28 on 2025-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0026_obtainmethod_debitextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obtainmethod',
            name='debitExtra',
        ),
        migrations.AddField(
            model_name='obtainmethod',
            name='creditExtra',
            field=models.CharField(blank=True, db_column='credit_extra', max_length=10, null=True),
        ),
    ]
