# Generated by Django 2.2.28 on 2025-07-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0027_auto_20250627_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestaccount',
            name='printChiefFullName',
            field=models.CharField(blank=True, db_column='print_chief_full_name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imprestaccount',
            name='printChiefPost',
            field=models.CharField(blank=True, db_column='print_chief_post', max_length=150, null=True),
        ),
    ]
