# Generated by Django 2.2.28 on 2025-07-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0028_auto_20250701_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True, verbose_name='Дата')),
                ('day_type', models.CharField(choices=[('workday', 'Рабочий день'), ('weekend', 'Выходной'), ('holiday', 'Праздничный'), ('shortened', 'Сокращенный день')], default='workday', max_length=10, verbose_name='Тип дня')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (праздник и т.д.)')),
                ('working_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=3, verbose_name='Количество рабочих часов')),
            ],
            options={
                'verbose_name': 'Производственный календарь',
                'verbose_name_plural': 'Производственный календарь',
                'db_table': 'production_calendar',
                'ordering': ['date'],
                'permissions': [('view_production_calendar', 'Просмотр'), ('edit_production_calendar', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='productioncalendar',
            index=models.Index(fields=['date'], name='production__date_f9aee3_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncalendar',
            index=models.Index(fields=['day_type'], name='production__day_typ_655ca2_idx'),
        ),
    ]
