# Generated by Django 2.2.28 on 2024-06-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('xv26eiId', models.IntegerField(db_column='xv26ei_id', primary_key=True, serialize=False)),
                ('xv26eicYear', models.SmallIntegerField(db_column='xv26eic_year')),
                ('xv26eihDateBegin', models.DateField(db_column='xv26eih_date_begin')),
                ('xv26eihDateEnd', models.DateField(blank=True, db_column='xv26eih_date_end', null=True)),
                ('xv26eihName', models.CharField(db_column='xv26eih_name', max_length=200)),
                ('xv26eirSumPlan', models.DecimalField(db_column='sum', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'estimate',
            },
        ),
    ]
