# Generated by Django 2.2.28 on 2025-06-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prepayment', '0080_auto_20250609_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=200)),
                ('approveDate', models.DateField(blank=True, db_column='create_date', null=True)),
                ('lockLevel', models.SmallIntegerField(db_column='lock_level')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
                'db_table': 'payment',
                'permissions': [('download_payment', 'Выгрузка'), ('view_payment', 'Просмотр'), ('edit_payment', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PaymentPrepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(db_column='status')),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=100)),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.PROTECT, to='payment.Payment')),
                ('prepayment', models.ForeignKey(db_column='prepayment_id', on_delete=django.db.models.deletion.PROTECT, to='prepayment.Prepayment')),
            ],
            options={
                'verbose_name': 'Выданный аванс в реестре',
                'verbose_name_plural': 'Выданные авансы в реестре',
                'db_table': 'payment_prepayment',
                'permissions': [('view_payment_prepayment', 'Просмотр'), ('edit_payment_prepayment', 'Редактирование')],
                'default_permissions': (),
                'unique_together': {('payment', 'prepayment')},
            },
        ),
    ]
