# Generated by Django 2.2.28 on 2025-06-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20250616_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='lockLevel',
            field=models.SmallIntegerField(db_column='lock_level', default=0),
        ),
    ]
