# Generated by Django 2.2.28 on 2025-06-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20250616_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='totalCount',
            field=models.IntegerField(db_column='total_count', default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='totalSum',
            field=models.DecimalField(db_column='total_sum', decimal_places=2, default=0, max_digits=10),
        ),
    ]
