# Generated by Django 2.2.28 on 2025-06-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20250616_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprepayment',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер лицевого счета'),
        ),
        migrations.AlterField(
            model_name='paymentprepayment',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.Payment'),
        ),
    ]
