# Generated by Django 2.2.28 on 2025-06-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20250617_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprepayment',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.Payment'),
        ),
    ]
