# Generated by Django 2.2.28 on 2025-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20250617_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprepayment',
            name='accountNumber',
            field=models.CharField(blank=True, db_column='account_number', max_length=20, null=True, verbose_name='Номер лицевого счета'),
        ),
    ]
