# Generated by Django 2.2.28 on 2025-06-18 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0019_auto_20250127_1734'),
        ('payment', '0007_auto_20250617_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprepayment',
            name='cardNumber',
            field=models.CharField(blank=True, db_column='card_number', max_length=16, null=True, verbose_name='Номер карты'),
        ),
        migrations.AddField(
            model_name='paymentprepayment',
            name='obtainMethod',
            field=models.ForeignKey(blank=True, db_column='obtain_method_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='guide.ObtainMethod'),
        ),
    ]
