# Generated by Django 2.2.28 on 2025-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20250618_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprepayment',
            name='deadline',
            field=models.DateField(blank=True, db_column='deadline', null=True),
        ),
    ]
