# Generated by Django 2.2.28 on 2025-06-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paymentprepayment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprepayment',
            name='repeatId',
            field=models.ForeignKey(blank=True, db_column='repeat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.PaymentPrepayment'),
        ),
    ]
