# Generated by Django 2.2.28 on 2025-06-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_paymentprepayment_repeatid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentprepayment',
            name='repeatId',
        ),
        migrations.AddField(
            model_name='paymentprepayment',
            name='repeatNext',
            field=models.ForeignKey(blank=True, db_column='repeat_next_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.PaymentPrepayment'),
        ),
    ]
