# Generated by Django 2.2.28 on 2025-06-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0022_auto_20250619_1237'),
        ('payment', '0011_auto_20250618_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(db_column='num')),
                ('createDate', models.DateField(db_column='create_date')),
                ('fileName', models.CharField(db_column='file_name', max_length=50)),
                ('createdBy', models.CharField(db_column='created_by', max_length=200)),
                ('createdAt', models.DateTimeField(db_column='created_at')),
                ('obtainMethod', models.ForeignKey(db_column='obtain_method_id', on_delete=django.db.models.deletion.PROTECT, to='guide.ObtainMethod')),
            ],
            options={
                'verbose_name': 'Файл выгрузки реестров',
                'verbose_name_plural': 'Файлы выгрузки реестров',
                'db_table': 'payment_file',
                'permissions': [('view_payment_file', 'Просмотр'), ('edit_payment_file', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='paymentprepayment',
            name='paymentFile',
            field=models.ForeignKey(blank=True, db_column='payment_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.PaymentFile'),
        ),
    ]
