# Generated by Django 2.2.28 on 2025-06-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20250620_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentprepayment',
            name='paymentFile',
        ),
        migrations.DeleteModel(
            name='PaymentFile',
        ),
    ]
