# Generated by Django 2.2.28 on 2025-06-20 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0022_auto_20250619_1237'),
        ('payment', '0013_auto_20250620_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='createdAt',
            field=models.DateTimeField(db_column='created_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='createdBy',
            field=models.CharField(db_column='created_by', default='admin', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='fileName',
            field=models.CharField(blank=True, db_column='file_name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='obtainMethod',
            field=models.ForeignKey(db_column='obtain_method_id', default=5, on_delete=django.db.models.deletion.PROTECT, to='guide.ObtainMethod'),
            preserve_default=False,
        ),
    ]
