# Generated by Django 2.2.28 on 2025-06-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0023_auto_20250620_1651'),
        ('payment', '0015_payment_filedatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='prepaidDest',
            field=models.ForeignKey(db_column='prepaid_dest_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='guide.PrepaidDest'),
            preserve_default=False,
        ),
    ]
