# Generated by Django 2.2.28 on 2025-06-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0080_auto_20250609_1052'),
        ('payment', '0016_payment_prepaiddest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprepayment',
            name='prepaymentItem',
            field=models.ForeignKey(blank=True, db_column='prepayment_item_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='prepayment.PrepaymentItem'),
        ),
    ]
