# Generated by Django 2.2.28 on 2025-06-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0080_auto_20250609_1052'),
        ('payment', '0017_paymentprepayment_prepaymentitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentprepayment',
            unique_together={('payment', 'prepaymentItem')},
        ),
        migrations.RemoveField(
            model_name='paymentprepayment',
            name='prepayment',
        ),
    ]
