# Generated by Django 2.2.28 on 2025-06-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20250625_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentprepayment',
            name='obtainMethod',
        ),
    ]
