# Generated by Django 2.2.28 on 2025-06-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_remove_paymentprepayment_obtainmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentprepayment',
            name='deadline',
        ),
    ]
