# Generated by Django 2.2.28 on 2025-06-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_remove_paymentprepayment_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aePeriod', models.DateField(db_column='ae_period')),
                ('aeNo', models.IntegerField(db_column='ae_no')),
                ('acplAccountDebit', models.SmallIntegerField(db_column='acpl_account_debit')),
                ('acplSubaccountDebit', models.SmallIntegerField(db_column='acpl_subaccount_debit')),
                ('acplCodeAnaliticDebit', models.CharField(db_column='acpl_code_analitic_debit', max_length=6)),
                ('acplCodeAnaliticDebit1', models.CharField(db_column='acpl_code_analitic_debit_1', max_length=3)),
                ('acplCodeAnaliticDebit2', models.CharField(db_column='acpl_code_analitic_debit_2', max_length=3)),
                ('acplAddSignDebit', models.CharField(db_column='acpl_add_sign_debit', max_length=10)),
                ('acplAccountCredit', models.SmallIntegerField(db_column='acpl_account_credit')),
                ('acplSubaccountCredit', models.SmallIntegerField(db_column='acpl_subaccount_credit')),
                ('acplCodeAnaliticCredit', models.CharField(db_column='acpl_code_analitic_credit', max_length=6)),
                ('acplCodeAnaliticCredit1', models.CharField(db_column='acpl_code_analitic_credit_1', max_length=3)),
                ('acplCodeAnaliticCredit2', models.CharField(db_column='acpl_code_analitic_credit_2', max_length=3)),
                ('acplAddSignCredit', models.CharField(db_column='acpl_add_sign_credit', max_length=10)),
                ('aeSum', models.DecimalField(db_column='ae_sum', decimal_places=2, max_digits=19)),
                ('paymentPrepayment', models.ForeignKey(db_column='payment_prepayment_id', on_delete=django.db.models.deletion.PROTECT, to='payment.PaymentPrepayment')),
            ],
            options={
                'verbose_name': 'Проводка по выплате',
                'verbose_name_plural': 'Проводки по выплате',
                'db_table': 'payment_entry',
                'permissions': [('view_payment_entry', 'Просмотр'), ('edit_payment_entry', 'Редактирование')],
                'default_permissions': (),
            },
        ),
    ]
