# Generated by Django 2.2.28 on 2025-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_paymententry'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='status',
            field=models.SmallIntegerField(blank=True, db_column='status', null=True),
        ),
    ]
