# Generated by Django 2.2.28 on 2025-06-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_paymententry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='approveDate',
            field=models.DateField(blank=True, db_column='approve_date', null=True),
        ),
    ]
