# Generated by Django 2.2.28 on 2025-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_paymententry_approvedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='approveBy',
            field=models.CharField(blank=True, db_column='approve_by', max_length=50, null=True),
        ),
    ]
