# Generated by Django 2.2.28 on 2025-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_paymententry_approveby'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='executor',
            field=models.CharField(blank=True, db_column='executor', max_length=200),
        ),
    ]
