# Generated by Django 2.2.28 on 2025-11-10 16:36

from django.db import migrations, models
import django.db.models.deletion

def insert_initial_data (apps, schema_editor):
    payment_dest = apps.get_model('payment', 'PaymentDest')
    payment_dest.objects.create (name = 'Командировочные расходы')
    payment_dest.objects.create (name = 'Подотчетные суммы')


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_payment_executor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=200)),
            ],
            options={
                'verbose_name': 'Назначение выплаты',
                'verbose_name_plural': 'Назначение выплаты',
                'db_table': 'payment_dest',
                'permissions': [('view_payment_dest', 'Просмотр'), ('edit_payment_dest', 'Редактирование')],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentDest',
            field=models.ForeignKey(blank=True, db_column='payment_dest_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.PaymentDest'),
        ),
        migrations.RunPython(insert_initial_data)
    ]
