# Generated by Django 2.2.28 on 2025-11-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_auto_20251110_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='prepaidDest',
            field=models.ForeignKey(blank=True, db_column='prepaid_dest_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='guide.PrepaidDest'),
        ),
    ]
