# Generated by Django 2.2.28 on 2025-11-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20251110_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mainAccountant',
            field=models.CharField(blank=True, db_column='main_accountant', max_length=200),
        ),
    ]
