# Generated by Django 2.2.28 on 2025-11-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_payment_mainaccountant'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='certificateNum',
            field=models.IntegerField(blank=True, db_column='certificate_num', default=0, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='certificateRegNum',
            field=models.IntegerField(blank=True, db_column='certificate_reg_num', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentprepayment',
            name='certificateNum',
            field=models.IntegerField(blank=True, db_column='certificate_num', default=0, null=True),
        ),
    ]
