# Generated by Django 2.2.28 on 2024-08-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prepayment', '0053_delete_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xv26eiId', models.SmallIntegerField(db_column='xv26ei_id')),
                ('pdId', models.IntegerField(blank=True, db_column='pd_id', null=True)),
                ('pdSource', models.SmallIntegerField(blank=True, db_column='pd_source', null=True)),
                ('sumFact', models.DecimalField(db_column='sum_fact', decimal_places=2, max_digits=10)),
                ('sumDelta', models.DecimalField(db_column='sum_delta', decimal_places=2, max_digits=10)),
                ('prepayment', models.ForeignKey(db_column='prepayment_id', on_delete=django.db.models.deletion.PROTECT, to='prepayment.Prepayment')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
                'db_table': 'fact',
                'default_permissions': [('download_fact', 'Выгрузка')],
            },
        ),
    ]
