# Generated by Django 2.2.28 on 2024-08-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'default_permissions': (), 'permissions': [('download_fact', 'Выгрузка')], 'verbose_name': 'Факт', 'verbose_name_plural': 'Факты'},
        ),
    ]
