# Generated by Django 2.2.28 on 2024-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inputDir', models.CharField(blank=True, db_column='input_dir', max_length=200)),
                ('outputDir', models.CharField(blank=True, db_column='output_dir', max_length=200)),
                ('employeeFileTemplate', models.CharField(db_column='employee_file_template', max_length=50)),
                ('prepaymentFileTemplate', models.CharField(db_column='prepayment_file_template', max_length=50)),
                ('estimateItemFileTemplate', models.CharField(db_column='estimate_item_file_template', max_length=50)),
                ('accountEntryFileTemplate', models.CharField(db_column='account_entry_file_template', max_length=50)),
                ('factFileTemplate', models.CharField(db_column='fact_file_template', max_length=50)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
