# Generated by Django 2.2.28 on 2024-06-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='orderFileTemplate',
            field=models.CharField(db_column='order_file_template', default='ГГГГ-ММ-ДД_075903.987_wc07p.csv', max_length=50),
        ),
    ]
