# Generated by Django 2.2.28 on 2024-06-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('pdId', models.IntegerField(db_column='pd_id', primary_key=True, serialize=False)),
                ('pdSource', models.SmallIntegerField(db_column='pd_source')),
                ('empOrgNo', models.IntegerField(db_column='emp_org_no')),
                ('xv26eiId', models.SmallIntegerField(blank=True, db_column='xv26ei_id')),
                ('orderId', models.CharField(blank=True, db_column='order_id', max_length=20)),
                ('orderIdUpd', models.CharField(blank=True, db_column='order_id_upd', max_length=20)),
                ('orderNo', models.CharField(blank=True, db_column='order_no', max_length=100)),
                ('order_date', models.DateField(blank=True, db_column='order_date')),
                ('bic', models.IntegerField(blank=True, db_column='bic')),
                ('sum', models.DecimalField(db_column='sum', decimal_places=2, max_digits=6)),
                ('acplAccount', models.SmallIntegerField(blank=True, db_column='acpl_account')),
                ('acplSubaccount', models.SmallIntegerField(blank=True, db_column='acpl_subaccount')),
            ],
            options={
                'db_table': 'prepayment',
            },
        ),
    ]
