# Generated by Django 2.2.28 on 2024-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='empFullName',
            field=models.CharField(db_column='emp_full_name', default='qwewe', max_length=200, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='empDivName',
            field=models.CharField(blank=True, db_column='emp_div_name', max_length=200, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='empDivNum',
            field=models.SmallIntegerField(blank=True, db_column='emp_div_num', null=True, verbose_name='Номер подразделения'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='empName',
            field=models.CharField(blank=True, db_column='emp_name', max_length=64, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='empNum',
            field=models.IntegerField(db_column='emp_num', verbose_name='Табельный'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='empPatronymic',
            field=models.CharField(blank=True, db_column='emp_patronymic', max_length=64, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='empProfName',
            field=models.CharField(blank=True, db_column='emp_prof_name', max_length=256, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='empSurname',
            field=models.CharField(blank=True, db_column='emp_surname', max_length=64, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='totalSum',
            field=models.DecimalField(db_column='total_sum', decimal_places=2, max_digits=10, verbose_name='Подотчетная сумма'),
        ),
    ]
