# Generated by Django 2.2.28 on 2024-06-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_exchangeprotocol'),
        ('prepayment', '0002_auto_20240617_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='wc07pOrder',
            field=models.ForeignKey(db_column='order_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='integration.WC07POrder'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='carryOverAdvanceReportDate',
            field=models.DateField(blank=True, db_column='carry_over_advance_report_date', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='carryOverAdvanceReportNum',
            field=models.IntegerField(blank=True, db_column='carry_over_advance_report_num', null=True, verbose_name='АО'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='carryOverSum',
            field=models.DecimalField(blank=True, db_column='carry_over_sum', decimal_places=2, max_digits=10, null=True, verbose_name='Сумма, руб.'),
        ),
    ]
