# Generated by Django 2.2.28 on 2024-06-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_prepaiddest'),
        ('prepayment', '0003_auto_20240618_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='document',
            field=models.ForeignKey(db_column='document_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='guide.Document'),
            preserve_default=False,
        ),
    ]
