# Generated by Django 2.2.28 on 2024-06-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0004_prepayment_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepayment',
            name='docName',
        ),
    ]
