# Generated by Django 2.2.28 on 2024-06-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_prepaiddest'),
        ('prepayment', '0006_auto_20240618_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaymentPurpose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deptExpense', models.CharField(blank=True, db_column='dept_expense', max_length=200, null=True)),
                ('account', models.CharField(blank=True, db_column='account', max_length=4, null=True)),
                ('expenditure', models.SmallIntegerField(blank=True, db_column='expenditure', null=True)),
                ('deptExpenditure', models.SmallIntegerField(blank=True, db_column='dept_expenditure', null=True)),
                ('extra', models.CharField(blank=True, db_column='extra', max_length=10, null=True)),
                ('missionPurpose', models.CharField(blank=True, db_column='mission_purpose', max_length=200, null=True)),
                ('reportDeadline', models.DateField(blank=True, db_column='report_deadline', null=True)),
                ('expenseCode', models.ForeignKey(blank=True, db_column='expense_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='guide.ExpenseCode')),
                ('prepaidDest', models.ForeignKey(db_column='prepaid_dest_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='guide.PrepaidDest')),
                ('prepayment', models.ForeignKey(db_column='prepayment_id', on_delete=django.db.models.deletion.PROTECT, to='prepayment.Prepayment')),
            ],
            options={
                'verbose_name': 'Назначение аванса',
                'verbose_name_plural': 'Назначения аванса',
                'db_table': 'prepayment_purpose',
                'default_permissions': (),
            },
        ),
    ]
