# Generated by Django 2.2.28 on 2024-06-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0007_prepaymentpurpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaymentpurpose',
            name='missionDest',
            field=models.CharField(blank=True, db_column='mission_dest', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prepaymentpurpose',
            name='missionFromDate',
            field=models.DateField(blank=True, db_column='mission_from_date', null=True),
        ),
        migrations.AddField(
            model_name='prepaymentpurpose',
            name='missionToDate',
            field=models.DateField(blank=True, db_column='mission_to_date', null=True),
        ),
    ]
