# Generated by Django 2.2.28 on 2024-06-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0008_auto_20240618_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaymentpurpose',
            name='deptExpense',
            field=models.CharField(db_column='dept_expense', max_length=200, null=True),
        ),
    ]
