# Generated by Django 2.2.28 on 2024-06-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_prepaiddest'),
        ('prepayment', '0009_auto_20240625_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(db_column='value', decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateTimeField(db_column='obtain_date', null=True, verbose_name='Дата')),
                ('obtainMethod', models.ForeignKey(blank=True, db_column='obtain_method_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='guide.ObtainMethod')),
            ],
        ),
    ]
