# Generated by Django 2.2.28 on 2024-06-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_prepaiddest'),
        ('prepayment', '0011_auto_20240626_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advance',
            new_name='PrepaymentItem',
        ),
        migrations.AlterModelTable(
            name='prepaymentitem',
            table='prepayment_item',
        ),
    ]
