# Generated by Django 2.2.28 on 2024-06-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0012_auto_20240626_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaymentitem',
            name='date',
            field=models.DateField(db_column='obtain_date', null=True, verbose_name='Дата'),
        ),
    ]
