# Generated by Django 2.2.28 on 2024-06-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0013_auto_20240626_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaymentitem',
            name='prepayment',
            field=models.ForeignKey(db_column='prepayment_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='prepayment.Prepayment'),
            preserve_default=False,
        ),
    ]
