# Generated by Django 2.2.28 on 2024-06-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_prepaiddest'),
        ('prepayment', '0015_auto_20240627_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='reportStatus',
            field=models.ForeignKey(blank=True, db_column='report_status_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportStatus', to='guide.Status'),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='spendedSum',
            field=models.DecimalField(blank=True, db_column='spended_sum', decimal_places=2, max_digits=10, null=True, verbose_name='Потраченная сумма'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='empDivNum',
            field=models.SmallIntegerField(blank=True, db_column='emp_div_num', null=True, verbose_name='Подразд.'),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='guide.Status'),
        ),
    ]
