# Generated by Django 2.2.28 on 2024-07-01 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_exchangeprotocol'),
        ('prepayment', '0017_prepayment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='iPrepayment',
            field=models.ForeignKey(db_column='integration_prepayment_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='integration.Prepayment'),
        ),
    ]
