# Generated by Django 2.2.28 on 2024-07-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0019_auto_20240701_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='reportDate',
            field=models.DateField(blank=True, db_column='report_date', null=True),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='reportNum',
            field=models.IntegerField(blank=True, db_column='report_num', null=True),
        ),
    ]
