# Generated by Django 2.2.28 on 2024-07-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0020_auto_20240701_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaymentitem',
            name='prepayment',
            field=models.ForeignKey(db_column='prepayment_id', on_delete=django.db.models.deletion.CASCADE, to='prepayment.Prepayment'),
        ),
        migrations.AlterField(
            model_name='prepaymentpurpose',
            name='prepayment',
            field=models.ForeignKey(db_column='prepayment_id', on_delete=django.db.models.deletion.CASCADE, to='prepayment.Prepayment'),
        ),
    ]
