# Generated by Django 2.2.28 on 2024-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0021_auto_20240701_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='reportAccountingNum',
            field=models.CharField(db_column='report_accounting_num', max_length=50, null=True),
        ),
    ]
