# Generated by Django 2.2.28 on 2024-07-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_prepaiddest'),
        ('prepayment', '0023_auto_20240702_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approveDocNum', models.CharField(blank=True, db_column='approve_doc_num', max_length=20, null=True)),
                ('approveDocDate', models.DateField(blank=True, db_column='approve_doc_date', null=True)),
                ('nomenclature', models.CharField(blank=True, db_column='nomenclature', max_length=100, null=True)),
                ('daysCount', models.SmallIntegerField(blank=True, db_column='days_count', null=True)),
                ('expenseSumCurrency', models.DecimalField(blank=True, db_column='expense_sum_currency', decimal_places=2, max_digits=10, null=True)),
                ('expenseSumRub', models.DecimalField(blank=True, db_column='expense_sum_rub', decimal_places=2, max_digits=10, null=True)),
                ('expenseSumVAT', models.DecimalField(blank=True, db_column='expense_sum_vat', decimal_places=2, max_digits=10, null=True)),
                ('deptExpense', models.CharField(blank=True, db_column='dept_expense', max_length=200, null=True)),
                ('accountingSum', models.DecimalField(blank=True, db_column='accounting_sum', decimal_places=2, max_digits=10, null=True)),
                ('debitAccount', models.IntegerField(blank=True, db_column='debit_account', null=True)),
                ('debitExpenseItem', models.CharField(blank=True, db_column='debit_expense_item', max_length=10, null=True)),
                ('debitExpenseWorkshop', models.CharField(blank=True, db_column='debit_expense_workshop', max_length=10, null=True)),
                ('debitExtra', models.CharField(blank=True, db_column='debit_extra', max_length=10, null=True)),
                ('creditAccount', models.IntegerField(blank=True, db_column='credit_account', null=True)),
                ('creditExpenseItem', models.CharField(blank=True, db_column='credit_expense_item', max_length=10, null=True)),
                ('creditDept', models.CharField(blank=True, db_column='credit_dept', max_length=10, null=True)),
                ('creditExtra', models.CharField(blank=True, db_column='credit_extra', max_length=10, null=True)),
                ('approveDocument', models.ForeignKey(db_column='approve_document_id', on_delete=django.db.models.deletion.PROTECT, to='guide.Document')),
                ('expenseCategory', models.ForeignKey(blank=True, db_column='expense_category_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='guide.ExpenseCategory')),
                ('expenseCode', models.ForeignKey(blank=True, db_column='expense_code_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='guide.ExpenseCode')),
                ('prepayment', models.ForeignKey(db_column='prepayment_id', on_delete=django.db.models.deletion.CASCADE, to='prepayment.Prepayment')),
            ],
            options={
                'verbose_name': 'Командировочный расход',
                'verbose_name_plural': 'Командировочные расходы',
                'db_table': 'prepayment_travel_expense',
                'default_permissions': (),
            },
        ),
    ]
