# Generated by Django 2.2.28 on 2024-07-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_prepaiddest'),
        ('prepayment', '0024_travelexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceReportItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approveDocNum', models.CharField(blank=True, db_column='approve_doc_num', max_length=20, null=True)),
                ('approveDocDate', models.DateField(blank=True, db_column='approve_doc_date', null=True)),
                ('nomenclature', models.CharField(blank=True, db_column='nomenclature', max_length=100, null=True)),
                ('expenseSumCurrency', models.DecimalField(blank=True, db_column='expense_sum_currency', decimal_places=2, max_digits=10, null=True)),
                ('expenseSumRub', models.DecimalField(blank=True, db_column='expense_sum_rub', decimal_places=2, max_digits=10, null=True)),
                ('expenseSumVAT', models.DecimalField(blank=True, db_column='expense_sum_vat', decimal_places=2, max_digits=10, null=True)),
                ('daysCount', models.SmallIntegerField(blank=True, db_column='days_count', null=True)),
                ('invoiceCode', models.CharField(blank=True, db_column='invoice_code', max_length=20, null=True)),
                ('itemType', models.SmallIntegerField(db_column='item_type')),
                ('approveDocument', models.ForeignKey(db_column='approve_document_id', on_delete=django.db.models.deletion.PROTECT, to='guide.Document')),
                ('expenseCategory', models.ForeignKey(blank=True, db_column='expense_category_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='guide.ExpenseCategory')),
                ('prepayment', models.ForeignKey(db_column='prepayment_id', on_delete=django.db.models.deletion.CASCADE, to='prepayment.Prepayment')),
            ],
            options={
                'verbose_name': 'Расход по авансовому отчету',
                'verbose_name_plural': 'Расходы по авансовому отчету',
                'db_table': 'advance_report_item',
                'default_permissions': (),
            },
        ),
    ]
