# Generated by Django 2.2.28 on 2024-07-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0025_advancereportitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelExpense',
        ),
    ]
