# Generated by Django 2.2.28 on 2024-07-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0026_delete_travelexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
                ('fileName', models.CharField(blank=True, db_column='file_name', max_length=50, null=True)),
                ('data', models.FileField(upload_to='')),
                ('prepayment', models.ForeignKey(db_column='prepayment_id', on_delete=django.db.models.deletion.CASCADE, to='prepayment.Prepayment')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'db_table': 'attachment',
                'default_permissions': (),
            },
        ),
    ]
