# Generated by Django 2.2.28 on 2024-07-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0027_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='data',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='fileName',
        ),
    ]
