# Generated by Django 2.2.28 on 2024-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0029_attachment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='date',
            field=models.DateTimeField(blank=True, db_column='attachment_date', null=True),
        ),
    ]
