# Generated by Django 2.2.28 on 2024-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0030_auto_20240703_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='reportComment',
            field=models.CharField(db_column='report_comment', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='date',
            field=models.DateTimeField(db_column='attachment_date'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(db_column='name', max_length=50),
        ),
    ]
