# Generated by Django 2.2.28 on 2024-07-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0031_auto_20240703_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceReportItemEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expenseCategory', models.ForeignKey(blank=True, db_column='advance_report_item_id', on_delete=django.db.models.deletion.PROTECT, to='prepayment.AdvanceReportItem')),
            ],
            options={
                'verbose_name': 'Бухгалтерская проводка',
                'verbose_name_plural': 'Бухгалтерские проводки',
                'db_table': 'advance_report_item_entity',
                'default_permissions': (),
            },
        ),
    ]
