# Generated by Django 2.2.28 on 2024-07-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0036_auto_20240716_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereportitementity',
            name='whOrderDate',
            field=models.DateTimeField(blank=True, db_column='wh_order_date', null=True),
        ),
        migrations.AddField(
            model_name='advancereportitementity',
            name='whOrderNum',
            field=models.CharField(blank=True, db_column='wh_order_num', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='advancereportitementity',
            name='accountingSum',
            field=models.DecimalField(blank=True, db_column='wh_order_sum', decimal_places=2, max_digits=10, null=True),
        ),
    ]
