# Generated by Django 2.2.28 on 2024-07-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0037_auto_20240716_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereportitementity',
            name='whOrderSum',
            field=models.DecimalField(blank=True, db_column='wh_order_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='advancereportitementity',
            name='accountingSum',
            field=models.DecimalField(blank=True, db_column='accounting_sum', decimal_places=2, max_digits=10, null=True),
        ),
    ]
