# Generated by Django 2.2.28 on 2024-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0038_auto_20240716_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereportitementity',
            name='creditKAU1',
            field=models.CharField(blank=True, db_column='credit_kau_1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitementity',
            name='creditKAU2',
            field=models.CharField(blank=True, db_column='credit_kau_2', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitementity',
            name='debitKAU1',
            field=models.CharField(blank=True, db_column='debit_kau_1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitementity',
            name='debitKAU2',
            field=models.CharField(blank=True, db_column='debit_kau_2', max_length=20, null=True),
        ),
    ]
