# Generated by Django 2.2.28 on 2024-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0039_auto_20240716_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', max_length=200, null=True, verbose_name='Телефон'),
        ),
    ]
