# Generated by Django 2.2.28 on 2024-07-30 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_expenseitem_expensetype'),
        ('prepayment', '0040_prepayment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='distribBank',
            field=models.DecimalField(blank=True, db_column='distrib_bank', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='distribBankMethod',
            field=models.ForeignKey(blank=True, db_column='distrib_bank_method_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='guide.ObtainMethod'),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='distribCarryover',
            field=models.DecimalField(blank=True, db_column='distrib_carryover', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='distribCarryoverReportNum',
            field=models.CharField(db_column='distrib_carryover_report_num', max_length=50, null=True, verbose_name='Номер А.О.'),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='distribSalary',
            field=models.DecimalField(blank=True, db_column='distrib_salary', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='distribSalaryDate',
            field=models.DateField(blank=True, db_column='distrib_salary_date', null=True),
        ),
    ]
