# Generated by Django 2.2.28 on 2024-08-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0042_auto_20240802_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereportitem',
            name='bankСommission',
            field=models.DecimalField(blank=True, db_column='bank_commission', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='comment',
            field=models.CharField(blank=True, db_column='comment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='service1Sum',
            field=models.DecimalField(blank=True, db_column='service_1_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='service1VAT',
            field=models.DecimalField(blank=True, db_column='service_1_vat', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='service2Sum',
            field=models.DecimalField(blank=True, db_column='service_2_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='service2VAT',
            field=models.DecimalField(blank=True, db_column='service_2_vat', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='sypherDate',
            field=models.DateField(blank=True, db_column='sypher_date', null=True),
        ),
    ]
