# Generated by Django 2.2.28 on 2024-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0044_auto_20240821_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereportitem',
            name='account',
            field=models.CharField(blank=True, db_column='account', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='extra',
            field=models.CharField(blank=True, db_column='extra', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='kau1',
            field=models.CharField(blank=True, db_column='kau_1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='kau2',
            field=models.CharField(blank=True, db_column='kau_2', max_length=10, null=True),
        ),
    ]
