# Generated by Django 2.2.28 on 2024-08-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0045_auto_20240821_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereportitem',
            name='route',
            field=models.CharField(blank=True, db_column='route', max_length=2, null=True),
        ),
    ]
