# Generated by Django 2.2.28 on 2024-08-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0046_advancereportitem_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereportitem',
            name='materialSum',
            field=models.DecimalField(blank=True, db_column='material_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='materialVAT',
            field=models.DecimalField(blank=True, db_column='material_vat', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='oilSum',
            field=models.DecimalField(blank=True, db_column='oil_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='oilVAT',
            field=models.DecimalField(blank=True, db_column='oil_vat', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='partSum',
            field=models.DecimalField(blank=True, db_column='part_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='partVAT',
            field=models.DecimalField(blank=True, db_column='part_vat', decimal_places=2, max_digits=10, null=True),
        ),
    ]
