# Generated by Django 2.2.28 on 2024-08-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0048_prepayment_accountcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='accountingEntryDate',
            field=models.DateField(blank=True, db_column='accounting_entry_date', null=True),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='lockLevel',
            field=models.SmallIntegerField(blank=True, db_column='lock_level', null=True),
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xv26eiId', models.SmallIntegerField(db_column='xv26ei_id')),
                ('pdId', models.IntegerField(db_column='pd_id')),
                ('pdSource', models.SmallIntegerField(db_column='pd_source')),
                ('prepayment', models.ForeignKey(db_column='prepayment_id', on_delete=django.db.models.deletion.PROTECT, to='prepayment.Prepayment')),
            ],
            options={
                'verbose_name': 'Бухгалтерская проводка в массиве',
                'verbose_name_plural': 'Бухгалтерские проводка в массиве',
                'db_table': 'accounting_entry',
                'default_permissions': [('download_accounting_entry', 'Выгрузка')],
            },
        ),
    ]
