# Generated by Django 2.2.28 on 2024-08-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0052_auto_20240822_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
