# Generated by Django 2.2.28 on 2024-08-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0054_auto_20240822_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountingEntry',
        ),
    ]
