# Generated by Django 2.2.28 on 2024-08-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0056_auto_20240823_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepayment',
            options={'default_permissions': (), 'permissions': [('view_prepaymentы', 'Просмотр'), ('edit_prepayments', 'Редактирование'), ('print_advance_report', 'Печать авансового отчета')], 'verbose_name': 'Аванс', 'verbose_name_plural': 'Авансы'},
        ),
    ]
