# Generated by Django 2.2.28 on 2024-08-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0061_auto_20240829_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='approveActionDate',
            field=models.DateField(blank=True, db_column='approve_action_date', null=True),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='reportAccountingNum',
            field=models.CharField(blank=True, db_column='report_accounting_num', max_length=50, null=True, verbose_name='Номер бухгалтерской справки'),
        ),
    ]
