# Generated by Django 2.2.28 on 2024-08-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0062_auto_20240830_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancereportitementity',
            name='creditKAU1',
            field=models.SmallIntegerField(blank=True, db_column='credit_kau_1', null=True),
        ),
        migrations.AlterField(
            model_name='advancereportitementity',
            name='creditKAU2',
            field=models.SmallIntegerField(blank=True, db_column='credit_kau_2', null=True),
        ),
        migrations.AlterField(
            model_name='advancereportitementity',
            name='debitKAU1',
            field=models.SmallIntegerField(blank=True, db_column='debit_kau_1', null=True),
        ),
        migrations.AlterField(
            model_name='advancereportitementity',
            name='debitKAU2',
            field=models.SmallIntegerField(blank=True, db_column='debit_kau_2', null=True),
        ),
    ]
