# Generated by Django 2.2.28 on 2024-08-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0063_auto_20240830_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancereportitementity',
            name='debitExpenseWorkshop',
            field=models.SmallIntegerField(blank=True, db_column='debit_expense_workshop', null=True),
        ),
    ]
