# Generated by Django 2.2.28 on 2024-08-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0065_auto_20240830_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancereportitementity',
            name='creditExpenseItem',
            field=models.SmallIntegerField(blank=True, db_column='credit_expense_item', null=True),
        ),
    ]
