# Generated by Django 2.2.28 on 2024-08-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0067_auto_20240830_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancereportitementity',
            name='deptExpense',
            field=models.SmallIntegerField(blank=True, db_column='dept_expense', null=True),
        ),
    ]
