# Generated by Django 2.2.28 on 2024-09-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0068_auto_20240830_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancereportitementity',
            name='accountingSum',
            field=models.DecimalField(db_column='accounting_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='advancereportitementity',
            name='creditAccount',
            field=models.IntegerField(db_column='credit_account', null=True),
        ),
        migrations.AlterField(
            model_name='advancereportitementity',
            name='debitAccount',
            field=models.IntegerField(db_column='debit_account', null=True),
        ),
        migrations.CreateModel(
            name='AdvanceReportInventoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invAnalysisPSO', models.SmallIntegerField(blank=True, db_column='inv_analysis_pso', null=True)),
                ('invAnalysisWarehouseNum', models.SmallIntegerField(blank=True, db_column='inv_analysis_warehouse_num', null=True)),
                ('whOrderNum', models.BigIntegerField(blank=True, db_column='wh_order_num', null=True)),
                ('whOrderDate', models.DateTimeField(blank=True, db_column='wh_order_date', null=True)),
                ('whOrderSum', models.DecimalField(blank=True, db_column='wh_order_sum', decimal_places=2, max_digits=10, null=True)),
                ('advanceReportItem', models.ForeignKey(blank=True, db_column='advance_report_item_id', on_delete=django.db.models.deletion.CASCADE, to='prepayment.AdvanceReportItem')),
            ],
            options={
                'verbose_name': 'Пункт списания ТМЦ',
                'verbose_name_plural': 'Пункты списания ТМЦ',
                'db_table': 'advance_report_inventory_item',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='advancereportitementity',
            name='advanceReportInventoryItem',
            field=models.ForeignKey(blank=True, db_column='advance_report_inventory_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='prepayment.AdvanceReportInventoryItem'),
        ),
    ]
