# Generated by Django 2.2.28 on 2024-11-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0069_auto_20240910_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='createdByFullName',
            field=models.CharField(db_column='created_by_fullname', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='updatedByAccountant',
            field=models.CharField(db_column='updated_by_accountant', max_length=200, null=True),
        ),
    ]
