# Generated by Django 2.2.28 on 2024-11-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0071_prepayment_contractidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereportitem',
            name='poGroup',
            field=models.SmallIntegerField(blank=True, db_column='po_group', null=True),
        ),
        migrations.AddField(
            model_name='advancereportitem',
            name='poType',
            field=models.SmallIntegerField(blank=True, db_column='po_type', null=True),
        ),
    ]
