# Generated by Django 2.2.28 on 2024-12-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0072_auto_20241113_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereportitementity',
            name='isStorno',
            field=models.SmallIntegerField(blank=True, db_column='is_storno', null=True),
        ),
    ]
