# Generated by Django 2.2.28 on 2024-12-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0073_advancereportitementity_isstorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereportitementity',
            name='approveDate',
            field=models.DateTimeField(blank=True, db_column='approve_date', null=True),
        ),
    ]
