# Generated by Django 2.2.28 on 2024-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0074_advancereportitementity_approvedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancereportitementity',
            name='approveDate',
            field=models.DateField(blank=True, db_column='approve_date', null=True),
        ),
    ]
