# Generated by Django 2.2.28 on 2025-01-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0075_auto_20241208_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancereportitem',
            name='approveDocNum',
            field=models.CharField(blank=True, db_column='approve_doc_num', max_length=30, null=True),
        ),
    ]
