# Generated by Django 2.2.28 on 2025-05-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0077_auto_20250227_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaymentpurpose',
            name='missionPurpose',
            field=models.CharField(blank=True, db_column='mission_purpose', max_length=400, null=True),
        ),
    ]
