# Generated by Django 2.2.28 on 2025-05-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0078_auto_20250520_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaymentEmpNum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empNum', models.IntegerField(db_column='emp_num', verbose_name='Табельный')),
                ('prepayment', models.ForeignKey(db_column='prepayment_id', on_delete=django.db.models.deletion.CASCADE, to='prepayment.Prepayment')),
            ],
            options={
                'verbose_name': 'Доступность авансового отчета',
                'verbose_name_plural': 'Доступность авансового отчета',
                'db_table': 'prepayment_emp_num',
                'permissions': [('view_prepayment_emp_nums', 'Просмотр'), ('edit_prepayment_emp_nums', 'Редактирование')],
                'default_permissions': (),
            },
        ),
    ]
