# Generated by Django 2.2.28 on 2025-06-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0079_prepaymentempnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='orderChangeDate',
            field=models.DateField(blank=True, db_column='order_change_date', null=True),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='orderChangeNum',
            field=models.CharField(blank=True, db_column='order_change_num', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prepayment',
            name='orderChanges',
            field=models.CharField(blank=True, db_column='order_changes', max_length=100, null=True),
        ),
    ]
