# Generated by Django 2.2.28 on 2025-07-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0081_auto_20250630_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancereportinventoryitem',
            name='whOrderNum',
            field=models.CharField(blank=True, db_column='wh_order_num', max_length=14, null=True),
        ),
    ]
