# Generated by Django 2.2.28 on 2025-12-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0082_auto_20250701_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepayment',
            options={'default_permissions': (), 'permissions': [('view_prepayments', 'Просмотр'), ('edit_prepayments', 'Редактирование'), ('print_advance_report', 'Печать авансового отчета'), ('view_advance_reports', 'Просмотр авансовых отчетов'), ('edit_advance_reports', 'Редактирование авансовых отчетов'), ('view_inventories', 'Просмотр описей массива авансовых отчетов'), ('downolad_inventories', 'Выгрузка описей массива авансовых отчетов'), ('view_owner_prepayments', 'Просмотр только свои'), ('edit_owner_prepayments', 'Редактирование только свои'), ('view_owner_advance_reports', 'Просмотр только своих авансовых отчетов'), ('edit_owner_advance_reports', 'Редактирование только своих авансовых отчетов'), ('view_owner_dept_prepayments', 'Просмотр своего подразделения'), ('edit_owner_dept_prepayments', 'Редактирование своего подразделения'), ('view_owner_dept_advance_reports', 'Просмотр авансовых отчетов своего подразделения'), ('edit_owner_dept_advance_reports', 'Редактирование авансовых отчетов своего подразделения'), ('submit_wc07p', 'WC07P. Отправка')], 'verbose_name': 'Аванс', 'verbose_name_plural': 'Авансы'},
        ),
        migrations.AddField(
            model_name='prepayment',
            name='wc07p_id',
            field=models.CharField(blank=True, db_column='wc07p_id', max_length=20, null=True),
        ),
    ]
