# Generated by Django 2.2.28 on 2024-06-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integration', '0003_wc07porder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(db_column='num')),
                ('createDate', models.DateField(db_column='create_date')),
                ('applicantPhone', models.CharField(blank=True, db_column='applicant_phone', max_length=20, null=True)),
                ('issuedSum', models.DecimalField(db_column='issued_sum', decimal_places=2, max_digits=10)),
                ('servicePayment', models.CharField(blank=True, db_column='service_payment', max_length=200, null=True)),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=500, null=True)),
                ('receivingDate', models.DateField(blank=True, db_column='receiving_date', null=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.PROTECT, to='integration.Employee')),
            ],
            options={
                'verbose_name': 'Заявление на аванс',
                'verbose_name_plural': 'Заявления на аванс',
                'db_table': 'request',
                'permissions': [('view_request', 'Просмотр'), ('edit_request', 'Редактирование'), ('view_owner_request', 'Просмотр только свои заявления'), ('edit_owner_request', 'Редактирование только свои заявления')],
                'default_permissions': (),
            },
        ),
    ]
