# Generated by Django 2.2.28 on 2024-06-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'default_permissions': (), 'permissions': [('view_requests', 'Просмотр'), ('edit_requests', 'Редактирование'), ('view_owner_requests', 'Просмотр только свои заявления'), ('edit_owner_requests', 'Редактирование только свои заявления')], 'verbose_name': 'Заявление на аванс', 'verbose_name_plural': 'Заявления на аванс'},
        ),
    ]
