# Generated by Django 2.2.28 on 2024-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20240611_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.SmallIntegerField(db_column='type', default=0),
            preserve_default=False,
        ),
    ]
