# Generated by Django 2.2.28 on 2024-06-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='createdAt',
            field=models.DateTimeField(db_column='created_at', default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='createdBy',
            field=models.CharField(db_column='created_by', default='', max_length=200),
            preserve_default=False,
        ),
    ]
