# Generated by Django 2.2.28 on 2024-06-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_prepaiddest'),
        ('request', '0005_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='imprestAccount',
            field=models.ForeignKey(db_column='imprest_account_id', default=7101, on_delete=django.db.models.deletion.PROTECT, to='guide.ImprestAccount'),
            preserve_default=False,
        ),
    ]
