# Generated by Django 2.2.28 on 2024-11-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_requestinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInventoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('cnt', models.SmallIntegerField(db_column='cnt')),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(db_column='total', decimal_places=2, max_digits=10)),
                ('requestInventory', models.ForeignKey(db_column='request_inventory_id', on_delete=django.db.models.deletion.PROTECT, to='request.RequestInventory')),
            ],
            options={
                'verbose_name': 'элемент МПЗ по заявлению',
                'verbose_name_plural': 'элементы МПЗ по заявлению',
                'db_table': 'request_inventory_item',
                'default_permissions': (),
            },
        ),
    ]
