# Generated by Django 2.2.28 on 2024-11-08 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_requestinventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinventoryitem',
            name='requestInventory',
            field=models.ForeignKey(db_column='request_inventory_id', on_delete=django.db.models.deletion.CASCADE, to='request.RequestInventory'),
        ),
    ]
