# Generated by Django 2.2.28 on 2024-11-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_auto_20241108_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='createdByFullName',
            field=models.CharField(db_column='created_by_fullname', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='updatedByAccountant',
            field=models.CharField(db_column='updated_by_accountant', max_length=200, null=True),
        ),
    ]
