# Generated by Django 2.2.28 on 2025-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_auto_20241108_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='updatedAtAccountant',
            field=models.DateTimeField(db_column='updated_at_accountant', null=True),
        ),
    ]
