# Generated by Django 2.2.28 on 2025-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_request_updatedataccountant'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='dailyAllowance',
            field=models.CharField(blank=True, db_column='daily_allowance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='dailyAllowanceDateFrom',
            field=models.DateField(blank=True, db_column='daily_allowance_date_from', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='dailyAllowanceDateTo',
            field=models.DateField(blank=True, db_column='daily_allowance_date_to', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='dailyAllowanceDays',
            field=models.IntegerField(blank=True, db_column='daily_allowance_days', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='dailyAllowanceRate',
            field=models.DecimalField(blank=True, db_column='daily_allowance_rate', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='dailyAllowanceSum',
            field=models.DecimalField(blank=True, db_column='daily_allowance_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='gsmAllowance',
            field=models.CharField(blank=True, db_column='gsm_allowance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='gsmAllowanceSum',
            field=models.DecimalField(blank=True, db_column='gsm_allowance_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='living',
            field=models.CharField(blank=True, db_column='living', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='livingDateFrom',
            field=models.DateField(blank=True, db_column='living_date_from', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='livingDateTo',
            field=models.DateField(blank=True, db_column='living_date_to', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='livingDays',
            field=models.IntegerField(blank=True, db_column='living_days', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='livingRate',
            field=models.DecimalField(blank=True, db_column='living_rate', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='livingSum',
            field=models.DecimalField(blank=True, db_column='living_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='orderAllowance',
            field=models.CharField(blank=True, db_column='order_allowance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='orderAllowanceSum',
            field=models.DecimalField(blank=True, db_column='order_allowance_sum', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='transfer',
            field=models.CharField(blank=True, db_column='transfer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='transferDateFrom',
            field=models.DateField(blank=True, db_column='transfer_date_from', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='transferDateTo',
            field=models.DateField(blank=True, db_column='transfer_date_to', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='transferSum',
            field=models.DecimalField(blank=True, db_column='transfer_sum', decimal_places=2, max_digits=10, null=True),
        ),
    ]
