# Generated by Django 2.2.28 on 2025-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_auto_20250530_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinventory',
            name='elementType',
            field=models.SmallIntegerField(blank=True, db_column='element_type', null=True),
        ),
    ]
