# Generated by Django 2.2.28 on 2025-06-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0019_auto_20250127_1734'),
        ('request', '0015_auto_20250603_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTravelExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True)),
                ('rate', models.DecimalField(blank=True, db_column='rate', decimal_places=2, max_digits=6, null=True)),
                ('dateFrom', models.DateField(blank=True, db_column='date_from', null=True)),
                ('dateTo', models.DateField(blank=True, db_column='date_to', null=True)),
                ('days', models.IntegerField(blank=True, db_column='days', null=True)),
                ('sum', models.DecimalField(blank=True, db_column='total_sum', decimal_places=2, max_digits=10, null=True)),
                ('type', models.SmallIntegerField(blank=True, db_column='expense_type', null=True)),
                ('expenseRate', models.ForeignKey(blank=True, db_column='expense_rate_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='guide.ExpenseRate')),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.PROTECT, to='request.Request')),
            ],
            options={
                'verbose_name': 'Расход на служебную поездку по заявлению',
                'verbose_name_plural': 'Расходы на служебную поездку по заявлению',
                'db_table': 'request_travel_expense',
                'default_permissions': (),
            },
        ),
    ]
