# Generated by Django 2.2.28 on 2025-06-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_requesttravelexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttravelexpense',
            name='request',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='request.Request'),
        ),
    ]
