# Generated by Django 2.2.28 on 2025-06-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0079_prepaymentempnum'),
        ('request', '0017_auto_20250604_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='dailyAllowance',
        ),
        migrations.RemoveField(
            model_name='request',
            name='dailyAllowanceDateFrom',
        ),
        migrations.RemoveField(
            model_name='request',
            name='dailyAllowanceDateTo',
        ),
        migrations.RemoveField(
            model_name='request',
            name='dailyAllowanceDays',
        ),
        migrations.RemoveField(
            model_name='request',
            name='dailyAllowanceRate',
        ),
        migrations.RemoveField(
            model_name='request',
            name='dailyAllowanceSum',
        ),
        migrations.RemoveField(
            model_name='request',
            name='gsmAllowance',
        ),
        migrations.RemoveField(
            model_name='request',
            name='gsmAllowanceSum',
        ),
        migrations.RemoveField(
            model_name='request',
            name='living',
        ),
        migrations.RemoveField(
            model_name='request',
            name='livingDateFrom',
        ),
        migrations.RemoveField(
            model_name='request',
            name='livingDateTo',
        ),
        migrations.RemoveField(
            model_name='request',
            name='livingDays',
        ),
        migrations.RemoveField(
            model_name='request',
            name='livingRate',
        ),
        migrations.RemoveField(
            model_name='request',
            name='livingSum',
        ),
        migrations.RemoveField(
            model_name='request',
            name='orderAllowance',
        ),
        migrations.RemoveField(
            model_name='request',
            name='orderAllowanceSum',
        ),
        migrations.RemoveField(
            model_name='request',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='request',
            name='transferDateFrom',
        ),
        migrations.RemoveField(
            model_name='request',
            name='transferDateTo',
        ),
        migrations.RemoveField(
            model_name='request',
            name='transferSum',
        ),
        migrations.AddField(
            model_name='request',
            name='carryOverPrepayment',
            field=models.ForeignKey(blank=True, db_column='carry_over_prepayment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carry_over_prepayment_id', to='prepayment.Prepayment'),
        ),
    ]
