# Generated by Django 2.2.28 on 2025-12-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_auto_20250606_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'default_permissions': (), 'permissions': [('view_requests', 'Просмотр'), ('edit_requests', 'Редактирование'), ('view_owner_requests', 'Просмотр только свои заявления'), ('edit_owner_requests', 'Редактирование только свои заявления'), ('submit_wc07p', 'WC07P. Отправка')], 'verbose_name': 'Заявление на аванс', 'verbose_name_plural': 'Заявления на аванс'},
        ),
    ]
