# Generated by Django 2.2.28 on 2025-12-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0019_auto_20251218_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='wc07p_id',
            field=models.CharField(blank=True, db_column='wc07p_id', max_length=20, null=True),
        ),
    ]
