# Generated by Django 2.2.28 on 2024-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingEntry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='acplCodeAnaliticCredit1',
            field=models.CharField(db_column='acpl_code_analitic_credit_1', default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='acplCodeAnaliticCredit2',
            field=models.CharField(db_column='acpl_code_analitic_credit_2', default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='acplCodeAnaliticDebit1',
            field=models.CharField(db_column='acpl_code_analitic_debit_1', default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='acplCodeAnaliticDebit2',
            field=models.CharField(db_column='acpl_code_analitic_debit_2', default=1, max_length=3),
            preserve_default=False,
        ),
    ]
