# Generated by Django 2.2.28 on 2024-08-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountingEntry', '0002_auto_20240823_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingentry',
            options={'default_permissions': (), 'permissions': [('download_accounting_entry', 'Выгрузка'), ('view_accounting_entry', 'Просмотр'), ('edit_accounting_entry', 'Редактирование')], 'verbose_name': 'Бухгалтерская проводка в массиве', 'verbose_name_plural': 'Бухгалтерские проводка в массиве'},
        ),
    ]
