# Generated by Django 2.2.28 on 2024-08-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountingEntry', '0004_auto_20240829_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingentry',
            options={'default_permissions': (), 'permissions': [('download_accounting_entry', 'Выгрузка'), ('view_accounting_entry', 'Просмотр'), ('edit_accounting_entry', 'Редактирование'), ('view_incomes_and_deductions', 'Просмотр справок доходов и удержаний'), ('download_incomes_and_deductions', 'Выгрузка справок доходов и удержаний')], 'verbose_name': 'Бухгалтерская проводка в массиве', 'verbose_name_plural': 'Бухгалтерские проводка в массиве'},
        ),
    ]
