# Generated by Django 2.2.28 on 2024-12-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepayment', '0072_auto_20241113_0014'),
        ('accountingEntry', '0005_auto_20240829_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingentry',
            name='advanceReportItemEntity',
            field=models.ForeignKey(blank=True, db_column='advance_report_item_entity_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='prepayment.AdvanceReportItemEntity'),
        ),
    ]
